[theme]
name = "DEDSEC"
author = "Archie"

[theme.options]
main_color = "(0, 255, 128)"

[fancygotchi]
rotation = 180

[fancygotchi.face]
position = "(110, 100)"

[fancygotchi.name]
position = "(160, 200)"
