# HOLO Theme Configuration
# Made by Archie

[theme]
name = "HOLO"
author = "Archie"
version = "1.0"

[theme.options]
bg_color = "(0, 0, 0)"
main_color = "(255, 150, 200)"

[theme.fonts]
main = "DejaVuSansMono"
bold = "DejaVuSansMono-Bold"

[ui]
fps = 0
font_name = "DejaVuSansMono"
font_size_status = 9
font_size_stats = 9

[ui.faces]
look_r = "( > _ > )"
look_l = "( < _ < )"
look_r_happy = "( ^ _ > )"
look_l_happy = "( < _ ^ )"
sleep = "( - _ - ) z z"
sleep2 = "( - _ - ) z z z"
awake = "( o _ o )"
bored = "( - _ - )"
intense = "( @ _ @ )"
cool = "( ⌐■_■ )"
happy = "( ^ _ ^ )"
excited = "( * o * )"
grateful = "( ^ _ ^ )b"
motivated = "( > _ < )"
demotivated = "( ; _ ; )"
smart = "( ◉ _ ◉ )"
lonely = "( . _ . )"
sad = "( T _ T )"
angry = "( ` _ ´ )"
friend = "( ^ _ ^ )/"
broken = "( x _ x )"
debug = "[ DEBUG ]"
upload = "[ >>> ]"
upload1 = "[ >>>> ]"
upload2 = "[ >>>>> ]"

[ui.web]
enabled = true

[fancygotchi]
rotation = 180

[fancygotchi.status]
position = "(5, 5)"
font_size = 9

[fancygotchi.channel]
position = "(5, 20)"
font_size = 9

[fancygotchi.aps]
position = "(5, 35)"
font_size = 9

[fancygotchi.uptime]
position = "(250, 5)"
font_size = 9

[fancygotchi.mode]
position = "(250, 20)"
font_size = 9

[fancygotchi.handshakes]
position = "(250, 35)"
font_size = 9

[fancygotchi.face]
position = "(110, 100)"

[fancygotchi.name]
position = "(160, 200)"
font_size = 12

[fancygotchi.friend_face]
position = "(10, 100)"

[fancygotchi.friend_name]
position = "(10, 160)"
font_size = 9

[fancygotchi.shakes]
position = "(10, 180)"
font_size = 9

[fancygotchi.pwnd_run]
position = "(10, 195)"
font_size = 9

[fancygotchi.pwnd_tot]
position = "(10, 210)"
font_size = 9
