[theme]
name = "LAIN"
author = "Archie"

[theme.options]
main_color = "(200, 150, 255)"

[fancygotchi]
rotation = 180

[fancygotchi.face]
position = "(110, 100)"

[fancygotchi.name]
position = "(160, 200)"
