[theme.dev]
refresh = -1
log = true
debug = false

[theme.options]
stealth_mode = false
fg_image = ""
bg_color = "#000000"
bg_image = "320x240-bg.png"
bg_anim_image = ""
font_sizes = [ 10, 8, 10, 55, 25, 9,]
font = "DejaVuSansMono"
font_bold = "DejaVuSansMono-Bold.ttf"
status_font = "DejaVuSansMono"
font_awesome = "font-awesome-solid.otf"
label_spacing = 9
size_offset = 5
cursor = ">"
base_text_color = [ "#ffffff",]
main_text_color = []
color_mode = [ "RGB", "RGB",]
boot_animation = true
boot_max_loops = 1
boot_total_duration = 4

[theme.widget.face]
position = [ 160, 110,]
text_font_size = "Huge"
color = [ "#ffffff",]
icon = true
icon_color = false
mask = false
refine = 150
image_type = "png"
f_awesome = false
zoom = 0
z_axis = 102

[theme.widget.name]
position = [ 160, 25,]
text_font_size = "Bold"
color = [ "#ffffff",]
z_axis = 100

[theme.widget.channel]
position = [ 285, 8,]
label = "CH"
label_font_size = "Medium"
text_font_size = "Medium"
label_spacing = 3
color = [ "#ffffff",]
z_axis = 0

[theme.widget.aps]
position = [ 225, 8,]
label = "AP"
label_font_size = "Medium"
text_font_size = "Medium"
label_spacing = 3
color = [ "#ffffff",]
z_axis = 0

[theme.widget.uptime]
position = [ 8, 8,]
label = "UP"
label_font_size = "Medium"
text_font_size = "Medium"
label_spacing = 3
color = [ "#ffffff",]
z_axis = 0

[theme.widget.mode]
position = [ 90, 8,]
text_font_size = "Bold"
color = [ "#ffffff",]
z_axis = 0

[theme.widget.status]
position = [ 160, 190,]
text_font_size = "Medium"
color = [ "#ffffff",]
wrap = true
max = 35
z_axis = 0

[theme.widget.shakes]
position = [ 8, 222,]
label = "PWND"
label_font_size = "Medium"
text_font_size = "Medium"
label_spacing = 3
color = [ "#ffffff",]
z_axis = 0

[theme.widget.clock]
position = [ 280, 222,]
text_font_size = "Medium"
color = [ "#ffffff",]
z_axis = 0
