[theme]
name = "MORTY"
author = "Archie"

[theme.options]
main_color = "(255, 200, 0)"

[fancygotchi]
rotation = 180

[fancygotchi.face]
position = "(110, 100)"

[fancygotchi.name]
position = "(160, 200)"
